# Pnadas 단일요건 Vlookup(merge)


> 데이터 프레임들을 database에서와 같은 병합을 하게 해주는 함수
>
> 엑셀의 vlookup같은 병합도 가능하다.

In [ ]:
import pandas as pd
from pathlib import Path
from icecream import ic

In [2]:
pd.set_option('display.max_rows', 6) # 최대 6줄까지 출력
url = Path("assets") / "02_02_merge01.xlsx"

In [3]:
df1 = pd.read_excel(url)
df1

      이름     제품
0    백철민   아이스티
1    박태인  레몬에이드
2    국지용  아메리카노
..   ...    ...
371  기주봉   아이스티
372  백승환  바닐라라떼
373  계승현  레몬에이드

[374 rows x 2 columns]

In [4]:
df2 = pd.read_excel(url, sheet_name=1)
df2

       제품    가격
0   아메리카노  3900
1   바닐라라떼  3900
2    까페라떼  3900
..    ...   ...
7     자몽티  4100
8   레몬에이드  4400
9   오렌지주스  3600

[10 rows x 2 columns]

In [ ]:
df3 = df1.merge(df2, how='left', on='제품')
df3.to_excel(Path("assets") / "merge_result01.xlsx")

# Pandas 다중요건 Vlookup(merge)




```python
df.merge(rignt, how='inner', on+None)
```
> right (인수 데이터프레임 혹은 시리즈)
> 병합할 객체
>
> how(인수는 'left','right','inner','corss' / 기본값은 'inner')
> 병합할 방식을 결정하는 인자.
> left: 왼쪽 데이터프레임의 키(key)만을 병합에 사용한다.(엑셀의 vlookup과 유사)
> right: 오른쪽 데이터프레임의 키(key)만을 병합에 사용한다.
> outer: 양쪽 데이터프레임의 키(key)들의 합집합을 병합에 사용한다.
> inner: 양쪽 데이터프레임의 키(key)들의 교집합을 병합에 사용한다.
> cross: 양쪽 데이터프레임의 곱집합(cartesian product)을 생헝한다.
>
> on(인수는 열의 레이블 또는 리스트 / 기본값은 None)
> 병합의 기준이 되는 열을 지정하는 인자. 기본 값은 양쪽데이터프레임에서 이름이 공통인 열들이 지정된다. 리스트로 입력하면 복수의 열을 기준으로 병합한다.
>

In [13]:
import pandas as pd;

pd.set_option('display.max_rows',6)
data1= [['송중기','별다방','아이스티'],
        ['권나현','콩다방','카페오레'],
        ['권보아','별다방','카페오레'],
        ['박효신','콩다방','아이스티'],
        ['김점수','별다방','카페오레']]
data2 = [['별다방','아이스티',4500],
        ['별다방','카페오레',4000],
        ['콩다방','아이스티',6000],
        ['콩다방','아이스티',6000],
        ['콩다방','카페오레',5500]]

df1 = pd.DataFrame(data1, columns=['이름','업체','음료'])
df2 = pd.DataFrame(data2, columns=['업체','음료','가격'])

In [16]:
df1.merge(df2,how='left',on=['업체','음료']) # == df1.merge(df2,how='left')

    이름   업체    음료    가격
0  송중기  별다방  아이스티  4500
1  권나현  콩다방  카페오레  5500
2  권보아  별다방  카페오레  4000
3  박효신  콩다방  아이스티  6000
4  박효신  콩다방  아이스티  6000
5  김점수  별다방  카페오레  4000

In [19]:
url = Path("assets") / "02_03_merge02.xlsx"
df3 =pd.read_excel(url)
df4 = pd.read_excel(url,sheet_name=1)
df4

      업체     제품    가격  구분
0  두솥도시락  돈까스정식  5700  일식
1  두솥도시락  산채비빔밥  5200  한식
2  두솥도시락  치킨도시락  6300  한식
3  종가도시락  돈까스정식  6600  일식
4  종가도시락  산채비빔밥  6700  한식
5  종가도시락  치킨도시락  5600  한식

In [25]:
df3.merge(df4,how='left').to_excel(Path("assets") / "merge_result02.xlsx",index=False)